/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg8_carlosnuila;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Nuila
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Clientes = new javax.swing.JDialog();
        jb_crearcliente = new javax.swing.JButton();
        jb_modificarCliente = new javax.swing.JButton();
        jb_eliminarCliente = new javax.swing.JButton();
        jd_CrearCliente = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nombreCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jt_apellidoCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rb_visa = new javax.swing.JRadioButton();
        rb_amex = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jt_dineroEfectivo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_universidad = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jt_numeroCuenta = new javax.swing.JTextField();
        jb_CrearCliente = new javax.swing.JButton();
        TarjetadeCredito = new javax.swing.ButtonGroup();
        Universidad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jb_clientes = new javax.swing.JButton();
        jb_inventario = new javax.swing.JButton();
        jb_hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_estadoMesa1 = new javax.swing.JLabel();
        jp_mesa1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_estadoMesa2 = new javax.swing.JLabel();
        jp_mesa2 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_estadoMesa3 = new javax.swing.JLabel();
        jp_mesa3 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_estadoMesa4 = new javax.swing.JLabel();
        jp_mesa4 = new javax.swing.JProgressBar();
        jb_iniciarSimulacion = new javax.swing.JButton();

        jd_Clientes.setTitle("Clientes");

        jb_crearcliente.setText("Crear Cliente");
        jb_crearcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearclienteMouseClicked(evt);
            }
        });

        jb_modificarCliente.setText("Modificar Cliente");

        jb_eliminarCliente.setText("Eliminar Cliente");

        javax.swing.GroupLayout jd_ClientesLayout = new javax.swing.GroupLayout(jd_Clientes.getContentPane());
        jd_Clientes.getContentPane().setLayout(jd_ClientesLayout);
        jd_ClientesLayout.setHorizontalGroup(
            jd_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ClientesLayout.createSequentialGroup()
                .addGroup(jd_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ClientesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jb_crearcliente)
                        .addGap(30, 30, 30)
                        .addComponent(jb_modificarCliente))
                    .addGroup(jd_ClientesLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jb_eliminarCliente)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jd_ClientesLayout.setVerticalGroup(
            jd_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ClientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jd_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearcliente)
                    .addComponent(jb_modificarCliente))
                .addGap(29, 29, 29)
                .addComponent(jb_eliminarCliente)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Cliente");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Apellido:");

        jLabel12.setText("Tarjeta de Credito:");

        TarjetadeCredito.add(rb_visa);
        rb_visa.setText("Visa");

        TarjetadeCredito.add(rb_amex);
        rb_amex.setText("Amex");

        jLabel13.setText("Efectivo:");

        jLabel14.setText("UNITEC:");

        Universidad.add(rb_universidad);
        rb_universidad.setText("Sí");
        rb_universidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_universidadMouseClicked(evt);
            }
        });

        Universidad.add(jRadioButton4);
        jRadioButton4.setText("No");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        jLabel15.setText("Número de Cuenta:");

        jt_numeroCuenta.setEditable(false);

        jb_CrearCliente.setText("Crear Cliente");
        jb_CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearClienteLayout = new javax.swing.GroupLayout(jd_CrearCliente.getContentPane());
        jd_CrearCliente.getContentPane().setLayout(jd_CrearClienteLayout);
        jd_CrearClienteLayout.setHorizontalGroup(
            jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                            .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel12))
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel11))
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel10))
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearClienteLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel14)))
                            .addGap(18, 18, 18)
                            .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addComponent(rb_universidad)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton4))
                                .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                                    .addComponent(rb_visa)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_amex))
                                .addComponent(jt_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt_dineroEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jb_CrearCliente)
                                .addComponent(jt_numeroCuenta))))
                    .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel9)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jd_CrearClienteLayout.setVerticalGroup(
            jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rb_visa)
                    .addComponent(rb_amex))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_dineroEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rb_universidad)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jb_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_clientes.setText("Administrar Clientes");
        jb_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clientesMouseClicked(evt);
            }
        });
        jPanel1.add(jb_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jb_inventario.setText("Inventario");
        jPanel1.add(jb_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jb_hora.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jb_hora.setText("12:00");
        jPanel1.add(jb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mesa 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        lb_estadoMesa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lb_estadoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 160, 20));

        jp_mesa1.setMaximum(15);
        jp_mesa1.setString(Integer.toString(jp_mesa1.getValue())+" Minutos");
        jp_mesa1.setStringPainted(true);
        jPanel1.add(jp_mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 280, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mesa 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Estado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        lb_estadoMesa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lb_estadoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 160, 20));

        jp_mesa2.setString(Integer.toString(jp_mesa2.getValue())+" Minutos");
        jp_mesa2.setStringPainted(true);
        jPanel1.add(jp_mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mesa 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        lb_estadoMesa3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lb_estadoMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 160, 20));

        jp_mesa3.setString(Integer.toString(jp_mesa3.getValue())+" Minutos");
        jp_mesa3.setStringPainted(true);
        jPanel1.add(jp_mesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 280, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mesa 4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Estado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        lb_estadoMesa4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lb_estadoMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 160, 20));

        jp_mesa4.setString(Integer.toString(jp_mesa4.getValue())+" Minutos");
        jp_mesa4.setStringPainted(true);
        jPanel1.add(jp_mesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 280, 20));

        jb_iniciarSimulacion.setText("Iniciar");
        jb_iniciarSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarSimulacionMouseClicked(evt);
            }
        });
        jPanel1.add(jb_iniciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clientesMouseClicked
        // TODO add your handling code here:
        jd_Clientes.pack();
        jd_Clientes.setModal(true);
        jd_Clientes.setVisible(true);
    }//GEN-LAST:event_jb_clientesMouseClicked

    private void jb_crearclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearclienteMouseClicked
        // TODO add your handling code here:
        jd_CrearCliente.pack();
        jd_CrearCliente.setModal(true);
        jd_CrearCliente.setVisible(true);

    }//GEN-LAST:event_jb_crearclienteMouseClicked

    private void jb_CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearClienteMouseClicked
        // TODO add your handling code here:
        AdministrarCliente ac = new AdministrarCliente("./Clientes.cans");
        ac.cargarArchivo();
        try {
            String nombre = jt_nombreCliente.getText();
            String apellido = jt_apellidoCliente.getText();
            String tarjetaCredito = "";
            if (rb_amex.isSelected()) {
                tarjetaCredito = "Amex";
            } else {
                tarjetaCredito = "Visa";
            }
            double efectivo = Double.parseDouble(jt_dineroEfectivo.getText());
            String universidad = "";
            int numeroCuenta = -1;
            if (rb_universidad.isSelected()) {
                universidad = "UNITEC";
                ArrayList<Cliente> temp = ac.getListaClientes();
                numeroCuenta = Integer.parseInt(jt_numeroCuenta.getText());
                int flag = 0;
                for (Cliente temp2 : temp) {
                    if (temp2.getNumeroCuenta() == numeroCuenta){
                        flag = 1;
                    }
                }
                if (flag == 1){
                    JOptionPane.showMessageDialog(jd_CrearCliente, "Ese numero de cuenta ya existe");
                    jt_numeroCuenta.setText("");
                }
            }
            
            Cliente nuevoCliente = new Cliente(nombre, apellido, tarjetaCredito, 0, efectivo, universidad, numeroCuenta);
            ac.setCliente(nuevoCliente);
            ac.escribirArchivo();
            
            jt_nombreCliente.setText("");
            jt_apellidoCliente.setText("");
            rb_visa.setSelected(true);
            rb_amex.setSelected(false);
            rb_universidad.setSelected(true);
            jRadioButton4.setSelected(false);
            jt_dineroEfectivo.setText("");
            jt_numeroCuenta.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_CrearCliente, "Ocurrió un error fatal");
        }
    }//GEN-LAST:event_jb_CrearClienteMouseClicked

    private void rb_universidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_universidadMouseClicked
        // TODO add your handling code here:
        jt_numeroCuenta.setEditable(true);
    }//GEN-LAST:event_rb_universidadMouseClicked

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        // TODO add your handling code here:
        jt_numeroCuenta.setText("");
        jt_numeroCuenta.setEditable(false);
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jb_iniciarSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarSimulacionMouseClicked
        // TODO add your handling code here:
        AdministrarCliente ac = new AdministrarCliente("./Clientes.cans");
        ac.cargarArchivo();
        clientesCreados = ac.getListaClientes();
        System.out.println(clientesCreados);
        HiloHora hiloHora = new HiloHora(jb_hora);
        hiloHora.start();
        Mesa mesa1 = new Mesa(lb_estadoMesa1, jp_mesa1);
        AdministrarBar adminMesa1 = new AdministrarBar(mesa1, clientesCreados);
        adminMesa1.start();
    }//GEN-LAST:event_jb_iniciarSimulacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    ArrayList<Cliente> clientesCreados;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TarjetadeCredito;
    private javax.swing.ButtonGroup Universidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton jb_CrearCliente;
    private javax.swing.JButton jb_clientes;
    private javax.swing.JButton jb_crearcliente;
    private javax.swing.JButton jb_eliminarCliente;
    private javax.swing.JLabel jb_hora;
    private javax.swing.JButton jb_iniciarSimulacion;
    private javax.swing.JButton jb_inventario;
    private javax.swing.JButton jb_modificarCliente;
    private javax.swing.JDialog jd_Clientes;
    private javax.swing.JDialog jd_CrearCliente;
    private javax.swing.JProgressBar jp_mesa1;
    private javax.swing.JProgressBar jp_mesa2;
    private javax.swing.JProgressBar jp_mesa3;
    private javax.swing.JProgressBar jp_mesa4;
    private javax.swing.JTextField jt_apellidoCliente;
    private javax.swing.JTextField jt_dineroEfectivo;
    private javax.swing.JTextField jt_nombreCliente;
    private javax.swing.JTextField jt_numeroCuenta;
    private javax.swing.JLabel lb_estadoMesa1;
    private javax.swing.JLabel lb_estadoMesa2;
    private javax.swing.JLabel lb_estadoMesa3;
    private javax.swing.JLabel lb_estadoMesa4;
    private javax.swing.JRadioButton rb_amex;
    private javax.swing.JRadioButton rb_universidad;
    private javax.swing.JRadioButton rb_visa;
    // End of variables declaration//GEN-END:variables
}
